version: "3.8"

services:     
  db:
    container_name: "golden"
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5456:5432"
    volumes:
      - type: volume
        source: my-golden-data
        target: /var/lib/postgresql12/data
        volume:
          nocopy: true
volumes:
  my-golden-data: # named volumes can be managed easier using docker-compose

